### ISSUE TITLE
Getting the current buffer's data

### ISSUE THREAD

**Issue by Zed-Bailey** [liquid600pgm/aglet#5]
Accessing the current buffers data(pixel RGB values) in an efficient, simple way.
I have not found another library with the functionality that can do this, digging into OpenGL it seems to be possible through the **PBO**, accessing it this way may be quite a cost(dragging it from the gpu to ram)

cheers Zed

**Comment by liquidev** [comment]
I have read about PBOs, they're designed for asynchronous pixel operations so they're actually quite cheap. One option would be to make the procedure that handles this `{.async.}`, but I haven't used asyncdispatch for implementing my own async procs from scratch so I would have to read some docs about that. Another option is to just use `glReadPixels`, but the big drawback is that it forces a sync between the GPU and the CPU, which can result in slowdowns.

I'll probably provide two APIs, `read` and `readSync`. The first will make use of `asyncdispatch`, the other will just use `glReadPixels`.

While we're at it, I may as well implement downloading data from Meshes and Textures. Should be quite simple, OpenGL already provides functions for that but again, I'll probably split the API into two versions, `download` and `downloadSync`.

**Comment by liquidev** [comment]
So after a bit of research it turns out that Nim's async API doesn't let you create your own futures easily… still, might be possible to do with async timers.
Regarding texture downloads, as far as I could tell it's not possible to do using PBOs, so there'll only be a sync version (named `download`). *If* I missed something, the API can always be changed.

**Comment by liquidev** [comment]
Just re-read the docs for `glGetTexImage` and it turns out that it *is* possible to use a PBO with it.

Regarding the async situation, I decided to roll with my own dispatcher because in a recent IRC chat @alaviss pointed out that syscalls are pretty costly. There aren't going to be any breaking API changes, ~~but there's going to be a new proc (`pollAsync`?), and it's going to be called on `swapBuffers` by default.~~ I'm going to reuse `pollEvents` for running the dispatcher loop to keep things simple.

**Comment by Zed-Bailey** [comment]
I haven't had much time to look into it myself but i've seen that SDL itself can also read the windows buffer with `SDL_RenderReadPixels()` [found in the top answer from this post](https://stackoverflow.com/questions/20579658/how-to-draw-pixels-in-sdl-2-0), I'm not sure how costly it will be though, but it may be something to look into?

**Comment by liquidev** [comment]
This is one of the goals of this issue. I will probably also implement a `window.defaultFramebuffer()` proc to obtain a special handle to the default framebuffer, and you'll be able to use `download` on that too.

As for how SDL2 handles that, I assume that under the OpenGL backend it just does a simple `glReadPixels` without using any PBOs. At least, that's what I could deduce from reading their documentation.

**Comment by liquidev** [comment]
Just pushed a commit for framebuffer downloads! :tada:
An example on how to take a screenshot of the default framebuffer can be found [here](https://github.com/liquid600pgm/aglet/blob/36b6bc1e8d8690956cd1b5abd69e38bb61dec9ae/tests/tcloud.nim#L137).

**Comment by Zed-Bailey** [comment]
Yay :D, i'm testing it out now

**Comment by liquidev** [comment]
So, after thinking a while I think I can leave out the Mesh part. This should be a different part of the API because mapping Buffer Objects to virtual memory is different than pixel transfers from framebuffers and textures.
